Final_Project/Models/Championship.cs
namespace Final_Project.Models
{
    public class Championship
    { 
        public PlayoffMatchup Finals { get; set; }
    }
}

Final_Project/Models/ErrorViewModel.cs
namespace Final_Project.Models
{
    public class ErrorViewModel
    {
        internal string RequestId;
        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Final_Project/Models/PlayoffMatchup.cs
namespace Final_Project.Models
{
    public class PlayoffMatchup
    {
        public PlayoffTeam2021 TopTeam { get; set; }
        public PlayoffTeam2021 BotTeam {get; set;}
        public string Round { get; set;}
       
    }
}

Final_Project/Models/PlayoffTeam2021.cs
namespace Final_Project.Models
{
    public class PlayoffTeam2021
    {
        public PlayoffTeam2021() { }

        public string Team { get; set; }=String.Empty;
        public bool QuarterFinals { get; set; }
        public bool SemiFinals { get; set; }
        public bool Championship { get; set; }
        public bool Winner { get; set; }
        public int Seed { get; set; }
        //public string QfOpp { get; set; } = String.Empty;
        //public string SfOpp { get; set; } = String.Empty;
        //public string ChampOpp { get; set; } = String.Empty;

    }
}

Final_Project/Models/Quarterfinals.cs
namespace Final_Project.Models
{
    public class QuarterFinals
    {
        public PlayoffMatchup FirstGame {get; set;}
        public PlayoffMatchup SecondGame { get; set;}
        public PlayoffMatchup ThirdGame { get; set;}
        public PlayoffMatchup FourthGame { get; set;}
       
    }
}

Final_Project/Models/Season2021.cs
namespace Final_Project.Models
{
    public class Season2021
    {
        public Season2021() { }

        public string Team { get; set; } = string.Empty;
        public string Week1 { get; set; } = string.Empty;
        public string Week2 { get; set; } = string.Empty;
        public string Week3 { get; set; } = string.Empty;
        public string Week4 { get; set; } = string.Empty;
        public string Week5 { get; set; } = string.Empty;
        public string Week6 { get; set; } = string.Empty;
        public string Week7 { get; set; } = string.Empty;
        public string Week8 { get; set; } = string.Empty;
        public string Week9 { get; set; } = string.Empty;
        public string Week10 { get; set; } = string.Empty;
        public string Week11 { get; set; } = string.Empty;
        public string Week12 { get; set; } = string.Empty;
        public string Week13 { get; set; } = string.Empty;
        public string Week14 { get; set; } = string.Empty;

    }
}

Final_Project/Models/SemiFinals.cs
namespace Final_Project.Models
{
    public class SemiFinals
    {
        public PlayoffMatchup TopGame { get; set; }
        public PlayoffMatchup BotomGame { get; set; }

    }
}

Final_Project/Models/Teams.cs
namespace Final_Project.Models
{
    public class Teams
    { public Teams() { }

        public string TeamName { get; set; }=String.Empty;
        public string Owner { get; set; } = String.Empty;
        public string Division { get; set; }= String.Empty;
        public string record { get; set; } = String.Empty;
        public bool MadePlayoffs { get; set; }

    }
}

Final_Project/Models/Tournament.cs
namespace Final_Project.Models
{
    public class Tournament
    {     
        public QuarterFinals Left { get; set; }
        public SemiFinals Middle { get; set; }
        public Championship Right { get; set; }
    }
}

Final_Project/Controllers/HomeController.cs
using Final_Project.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Final_Project.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Final_Project/Controllers/Playoffs2021Controller.cs
using Final_Project.Models;
using Microsoft.AspNetCore.Mvc;

namespace Final_Project.Controllers
{
    public class Playoffs2021Controller : Controller
    {
        private readonly IPlayoffs2021Repository _repo;
        public Playoffs2021Controller(IPlayoffs2021Repository repo)
        {
            this._repo = repo;
        }

        public IActionResult Index()
        {   
            var qfTeams = _repo.GetQFGames().ToList();
            var sfTeams=_repo.GetSFGames().ToList();
            var champTeams = _repo.GetChampionshipGame().ToList();
            var matchup1 = new PlayoffMatchup()
            
            {
                TopTeam = qfTeams[0],
                BotTeam = qfTeams[6],
                Round= "qf",
              
            };

            var matchup2 = new PlayoffMatchup()
            {
                TopTeam = qfTeams[4],
                BotTeam = qfTeams[5],
                Round="qf",
        
            };
            var matchup3 = new PlayoffMatchup()
            {
                TopTeam = qfTeams[1],
                BotTeam = qfTeams[7],
                Round= "qf",
         
            };
            var matchup4 = new PlayoffMatchup()
            {
                TopTeam = qfTeams[2],
                BotTeam = qfTeams[3],
                Round= "qf",
          
            };
            var matchup5 = new PlayoffMatchup()
            {
                TopTeam = sfTeams[0],
                BotTeam = sfTeams[3],
                Round="sf",
         
            };
            var matchup6 = new PlayoffMatchup()
            {
                TopTeam = sfTeams[1],
                BotTeam = sfTeams[2],
                Round= "sf",
           
            };
            var matchup7 = new PlayoffMatchup()
            {
                TopTeam = champTeams[1],
                BotTeam = champTeams[0],
                Round="championship",
          
            };
            var matchups = new List<PlayoffMatchup>()
            {
                matchup1,
                matchup2,
                matchup3,
                matchup4,
                matchup5,
                matchup6,
                matchup7,
            };
            var qfs = new QuarterFinals()
            {
                FirstGame = matchup1,
                SecondGame = matchup2,
                ThirdGame = matchup3,
                FourthGame = matchup4,
            };
            var sfs = new SemiFinals()
            {
                TopGame = matchup5,
                BotomGame = matchup6,
            };

            var cg = new Championship()
            {
                Finals = matchup7
            };
            var tournament = new Tournament()
            {
                Left = qfs,
                Middle = sfs,
                Right = cg,

            };

            return View(tournament);
        }
    }
}

Final_Project/Controllers/Season2021Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Final_Project.Controllers
{
    public class Season2021Controller : Controller
    {
        private readonly ISeason2021Repository repo;

        public Season2021Controller(ISeason2021Repository repo)
        {
            this.repo = repo;
        }

        public IActionResult Index()
        {
            var records = repo.GetSeason();
            return View(records);
        }
    }
}

Final_Project/Controllers/TeamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Final_Project.Controllers
{
    public class TeamsController : Controller
    {
        private readonly ITeamsRepository repo;
        public TeamsController(ITeamsRepository repo)
        {
            this.repo = repo;
        }

        public IActionResult Index()
        {
            var teams = repo.GetAllTeams();
            return View(teams);
        }
    }
}

Final_Project/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<main>
    <div class="heading">
        <h1 class="DSBC"> The Deep South Brunch Club</h1>
        <p>Home of the Most OK Fantasy Football.</p>
    </div>
    <Section class="flex-container">
        <div class="image">
            <img src="/css/Resized_20220822_220616.jpeg" alt="Trophy"><img  />
        </div>
        <div class="about">
            <h4>About The League</h4>
            <p >
                Here at the Deep South Brunch Club we know all about what it means to be a fantasy football team owner.
                Sometimes it means making absolutely ridiculous fantasy decisions in hopes that they can help you make the playoffs.
                Other times its hitting the lottery and picking up Christian McCaffrey off the waiver wire because your league-mate dropped him on accident.
                Most of the time though, it's watching in horror as your first 3 draft picks get injured by the 3rd week of the season and making their horrrific injuries about us.
                That being said, Our leage has quite a few things going for it. For starters, our league has managed to keep  the same commisioner and also most of its players since year one.
                We always honor the rules with just the right amount of complaining. We always have the craziest team names (some of which I edited to show this as my project). Trash talk 
                is always at an all time high Week in and Week out. And Most importantly, The winner gets a sick trophy that they get to engrave their team name on and gets hold on to the trophy to display 
                for bragging rights for an entire year.
        </div>
         </Section>
        <section class="rules">
            <h4 style="text-align:center"> League Rules and Regulations</h4>
            <p>
                <ul>
                    <li>
                        Draft order determined by a college football pick'em contest
                    </li>
                    <li>
                       Scoring- Half-Point per Recption 
                    </li>
                    <li>
                        10 team League 
                    </li>
                    <li>
                        Standard per yard and per TD scoring 
                    </li>
                    <li>
                        6 team playoffs with the top teams of each division having a first round bye
                    </li>
                    <li>
                        First place gets bragging rights and gets to hold the trophy for a year
                    </li>
                    <li>
                        Last place gets reprimanded according to the punishemnt agreed upon at the start of the season
                     </li>
                     <li> Mandated and required Fun</li>
                </ul>
            
            
                <div>
                    <h4> Why I created This</h4>
                    <p>This Leage is one of the most fun things my friends and I do each year and I wanted to create something that could serve as a tool to brag  </p>
                </div>
            </p>
        </section>
   

</main>

Final_Project/Views/Playoffs2021/Index.cshtml
@model Tournament
<head>
    <link href="~/css/PlayoffIndexcshtml.css" rel="stylesheet" />
</head>
 

<main id="tournament">
    <section class="container">
        <div class="flexleft">
            <h4>Quarter Finals</h4>
            <span class="spacer">&nbsp;</span>
           
            <div>
                <div class="helper">
                    <span style="font-weight:bold">@Model.Left.FirstGame.TopTeam.Team</span>
                    <div class="game">
                        <hr class="brlines" />
                        @Model.Left.FirstGame.BotTeam.Team
                        <hr class="brlines" />
                    </div>
                </div>
                <div class="helper">
                    <span> @Model.Left.SecondGame.TopTeam.Team</span>
                    <div class="game">
                        <hr class="brlines" />
                        <p style="font-weight:bold">@Model.Left.SecondGame.BotTeam.Team </p>
                        <hr class="brlines" />
                   
                    </div>
                </div>
                <div class="helper">
                    <span style="font-weight:bold">@Model.Left.ThirdGame.TopTeam.Team</span>
                    <div class="game">
                        <hr class="brlines" />
                        @Model.Left.ThirdGame.BotTeam.Team
                        <hr class="brlines" />
                  
                    </div>
                </div>
                <div class="helper">
                    <span>@Model.Left.FourthGame.TopTeam.Team</span>
                    <div class="game">
                        <hr class="brlines" />
                      <p style=font-weight:bold> @Model.Left.FourthGame.BotTeam.Team</p>
                        <hr class="brlines" />
                        
                    </div>
                </div>
            </div>
        </div>
        <div class="flexmid">

            <h4>Semi-Finals</h4>
            <span class="spacer">&nbsp;</span>
          

            <div class="helper">
                <span class="gamespacer">&nbsp;</span>
                <span>@Model.Middle.TopGame.TopTeam.Team</span>
                <div class="game">
                    <hr class="brlines" />
                   <p style="font-weight:bold"> @Model.Middle.TopGame.BotTeam.Team</p>
                    <hr class="brlines" />
                    </div>
                <span class="spacer">&nbsp;</span>
                <span class="spacer">&nbsp;</span>
                <span class="spacer">&nbsp;</span>
            </div>
            <div class="helper">
                <span class="gamespacer">&nbsp;</span>
                <span>@Model.Middle.BotomGame.TopTeam.Team</span>
                <div class="game">
                    <hr class="brlines" />
                   <p style="font-weight:bold"> @Model.Middle.BotomGame.BotTeam.Team</p>
                    <hr class="brlines" />
                </div>
            </div>
        </div>

        <div class="flexright">

            <h4>Championship Game</H4>

            <div class="right">
                <div class="helper">
                    <span style="font-weight:bold">@Model.Right.Finals.TopTeam.Team --- Champion!!!</span>
                    <div class="game">
                        <hr class="brlines" />
                        @Model.Right.Finals.BotTeam.Team
                        <hr class="brlines" />
                    </div>
                </div>
            </div>
        </div>
        <div> 
            
            
        </div>
    </section>
</main>

Final_Project/Views/Season2021/Index.cshtml
<head>
    
</head>
@model IEnumerable<Season2021>

    <h1 id="Title">2021 Regular Season</h1>

  <body>

        <p>

            Here is a quick look at the results from last year's regular season
        </p>



   
    <table class="table">
        <tr>
            <th class="c1"> Team </th>
            <th class="c2"> Game 1 </th>
            <th class="c3"> Game 2 </th>
            <th class="c1"> Game 3 </th>
            <th class="c2">  Game 4 </th>
            <th class="c3"> Game 5 </th>
            <th class="c1"> Game 6 </th>
            <th class="c2"> Game 7 </th>
            <th class="c3"> Game 8 </th>
            <th class="c1"> Game 9 </th>
            <th class="c2"> Game 10 </th>
            <th class="c3"> Game 11 </th>
            <th class="c1"> Game 12 </th>
            <th class="c2"> Game 13 </th>
            <th class="c3"> Game 14 </th>
        </tr>

        @foreach (var record in Model)
    {
        <tr>
            <td class="c1">@record.Team</td>
            <td class="c2">@record.Week1</td>
            <td class="c3">@record.Week2</td>
            <td class="c1">@record.Week3</td>
            <td class="c2">@record.Week4</td>
            <td class="c3">@record.Week5</td>
            <td class="c1">@record.Week6</td>
            <td class="c2">@record.Week7</td>
            <td class="c3">@record.Week8</td>
            <td class="c1">@record.Week9</td>
            <td class="c2">@record.Week10</td>
            <td class="c3">@record.Week11</td>
            <td class="c1">@record.Week12</td>
            <td class="c2">@record.Week13</td>
            <td class="c3">@record.Week14</td>
        </tr>
    }
     
     </table>
 </body>
 

Final_Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Southern Brunch Club Fantasy Football</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Final_Project.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="C:\Users\fulto\Desktop\Final_Project\Final_Project\StyleSheets\" />
    <link href="Final_Project.styles.css" rel="stylesheet">
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
             <img id="Logo" alt="DSBC Logo" src="~/css/Logo.png" />
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teams" asp-action="Index">Teams</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Season2021" asp-action="Index">2021 Regular Season</a>
                        </li>
                       <li class="nav-item">
                           <a class="nav-link text-dark" asp-area="" asp-controller="Playoffs2021" asp-action="Index">2021 Post Season</a>
                       </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DSBC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>